Update build-kernel.yml

diff --git a/.github/workflows/build-kernel.yml b/.github/workflows/build-kernel.yml
--- a/.github/workflows/build-kernel.yml
+++ b/.github/workflows/build-kernel.yml
@@ -1,5 +1,13 @@
 name: Build Kernel
 on:
+  push: 
+    branches:
+          - "Crtl-KSUNext-SUSFS" 
+  pull_request: 
+     branches: 
+          - "kernel-tree_lancelot" 
+     paths:
+          - ".github/workflows/build-kernel.yml"
   workflow_dispatch:
 
 jobs:
@@ -25,6 +33,7 @@ jobs:
             KERNELSU_TAG
             KSU_EXPECTED_SIZE
             KSU_EXPECTED_HASH
+            KSU_NEXT_REVERT
             KSU_REVERT
             ADD_KPROBES_CONFIG
             KSU_HOOKS_PATCH
@@ -60,6 +69,7 @@ jobs:
             SOURCE_BOOT_IMAGE
             DISABLE_LTO
             DISABLE_CC_WERROR
+            FIX_MOBILE_DATA
             REMOVE_UNUSED_PACKAGES
             ENABLE_CCACHE
             ADD_LOCALVERSION_TO_FILENAME
@@ -74,7 +84,7 @@ jobs:
       if: env.REMOVE_UNUSED_PACKAGES == 'true'
       uses: jlumbroso/free-disk-space@main
       with:
-        tool-cache: ture
+        tool-cache: true
         android: false
         dotnet: true
         haskell: true
@@ -209,32 +219,94 @@ jobs:
             echo "HAVE_SOURCE_BOOT_IMAGE=true" >> $GITHUB_ENV
         fi
 
+
+
+
     - name: Setup KernelSU
       if: env.ENABLE_KERNELSU == 'true'
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
-        
         curl -LSs "https://raw.githubusercontent.com/rifsxd/KernelSU-Next/next/kernel/setup.sh" | bash -s next-susfs-4.14
         KSU_VERSION=$(cd KernelSU-Next && expr $(/usr/bin/git rev-list --count HEAD) + 10200)
 
+        
+
         git clone https://gitlab.com/simonpunk/susfs4ksu.git -b kernel-4.14
-        cd susfs4ksu
-        git switch 516e40c6 --detach
-        cd ..
-        cp ./susfs4ksu/kernel_patches/include/linux/susfs.h $GITHUB_WORKSPACE/kernel_workspace/android-kernel/include/linux/
-        cp ./susfs4ksu/kernel_patches/fs/susfs.c $GITHUB_WORKSPACE/kernel_workspace/android-kernel/fs/
-        cp ./susfs4ksu/kernel_patches/50_add_susfs_in_kernel-4.14.patch $GITHUB_WORKSPACE/kernel_workspace/android-kernel
-        patch -p1 < 50_add_susfs_in_kernel-4.14.patch || echo "Patch failed, skipping."
 
-        sed -i '/struct ratelimit_state ratelimit;/a\#if defined(CONFIG_KSU_SUSFS) && !defined(ANDROID_KABI_RESERVE)\nu64 android_kabi_reserved2;\n#endif\nANDROID_KABI_RESERVE(1);\nANDROID_KABI_RESERVE(2);' $GITHUB_WORKSPACE/kernel_workspace/android-kernel/include/linux/sched/user.h
 
-        ls $GITHUB_WORKSPACE/kernel_workspace/android-kernel/include/linux/susfs.h
-        ls $GITHUB_WORKSPACE/kernel_workspace/android-kernel/fs/susfs.c
 
-        grep -r "susfs_is_sus_su_hooks_enabled" .
+        sed -i '/^#define CMD_SUSFS_SUS_SU 0x60000/a #define USER_STRUCT_KABI2_NON_ROOT_USER_APP_PROFILE 16777216 // 1 << 24, for distinguishing root/no-root granted user app process' $GITHUB_WORKSPACE/kernel_workspace/android-kernel/susfs4ksu/kernel_patches/include/linux/susfs_def.h
+
+
+        sed -i '/^struct user_struct {/,/^};/ s/^};/\
+          #ifdef CONFIG_KSU_SUSFS\
+              u64 android_kabi_reserved2;\
+          #endif\
+              \/\/ Android KABI reserved fields\
+              u64 android_kabi_reserved1;\
+              u64 android_kabi_reserved3;\
+              u64 android_kabi_reserved4;\
+              u64 android_kabi_reserved5;\
+              u64 android_kabi_reserved6;\
+              u64 android_kabi_reserved7;\
+              u64 android_kabi_reserved8;\
+          };/' $GITHUB_WORKSPACE/kernel_workspace/android-kernel/include/linux/sched/user.h
+
+        cat <<EOF >> arch/arm64/configs/defconfig
+          # KernelSU configurations
+          CONFIG_KSU=y
+          CONFIG_KSU_DEBUG=y
+          CONFIG_KSU_SUSFS=y
+          # SUSFS configurations
+          CONFIG_KSU_SUSFS_SUS_PATH=y
+          CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y
+          CONFIG_KSU_SUSFS_SUS_MOUNT=y
+          CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y
+          CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y
+          CONFIG_KSU_SUSFS_SUS_KSTAT=y
+          CONFIG_KSU_SUSFS_SUS_OVERLAYFS=y
+          CONFIG_KSU_SUSFS_TRY_UMOUNT=y
+          CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=y
+          CONFIG_KSU_SUSFS_SPOOF_UNAME=y
+          CONFIG_KSU_SUSFS_ENABLE_LOG=y
+          CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y
+          CONFIG_KSU_SUSFS_SPOOF_PROC_CMDLINE=y
+          CONFIG_KSU_SUSFS_OPEN_REDIRECT=y
+          CONFIG_KSU_SUSFS_SUS_SU=y
+        EOF
+
+
+        mkdir $GITHUB_WORKSPACE/kernel_workspace/android-kernel/KernelSU/
+ 
+        cp $GITHUB_WORKSPACE/kernel_workspace/android-kernel/susfs4ksu/kernel_patches/KernelSU/* $GITHUB_WORKSPACE/kernel_workspace/android-kernel/KernelSU/
+
+        cp $GITHUB_WORKSPACE/kernel_workspace/android-kernel/susfs4ksu/kernel_patches/50_add_susfs_in_kernel-4.14.patch $GITHUB_WORKSPACE/kernel_workspace/android-kernel/
+
+        cp $GITHUB_WORKSPACE/kernel_workspace/android-kernel/susfs4ksu/kernel_patches/include/linux/* $GITHUB_WORKSPACE/kernel_workspace/android-kernel/include/linux/
+
+        cp $GITHUB_WORKSPACE/kernel_workspace/android-kernel/susfs4ksu/kernel_patches/fs/* $GITHUB_WORKSPACE/kernel_workspace/android-kernel/fs/
+
+        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel/KernelSU
+
+        echo "[+] Patch 10 enable susfs for ksu ... "
+
+        patch -p1 < 10_enable_susfs_for_ksu.patch || echo "Patch 10 enable failed, skipping."
+
+        cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel/
+
+        echo "[+] Patch 50 add susfs in kernel 4.14 ..."
+
+        patch -p1 < 50_add_susfs_in_kernel-4.14.patch || echo "Patch 50 add susfs failed, skipping."
+
 
         echo "KSUVER=$KSU_VERSION" >> $GITHUB_ENV
+
+
+       
         
+
+
+
     - name: Setup Configuration for Kernel
       run: |
         cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
@@ -294,6 +366,12 @@ jobs:
             else
                 echo "CONFIG_MMC_CRYPTO_LEGACY=y" >> arch/${{ env.KERNEL_ARCH }}/configs/${{ env.KERNEL_CONFIG }}
             fi
+        fi
+        if [ ${{ env.FIX_MOBILE_DATA }} = true ]; then
+            rm -rf drivers/misc/mediatek/connectivity
+            cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel/drivers/misc/mediatek
+            git clone https://github.com/Jbub5/connectivity.git --depth=1
+            cd $GITHUB_WORKSPACE/kernel_workspace/android-kernel
         fi
 
     - name: Setup ccache
